--- #YAML:1.0
name:                Lingua-UK-Jcuken
version:             1.02
abstract:            Convert between QWERTY/JCUKEN
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Text::Iconv:                   1.4
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Serguei Trouchelle <stro@railways.dp.ua>
